### ISSUE TITLE
Landing Page Skeleton

### ISSUE THREAD

**Issue by chrispetrone** [devxp-ca/devxp#10]
Barebones Landing Page w/ structure, no functionality
-> info section
-> login/link account button opens/redirects to login page
-> space for graphic?

**Comment by keanelekenns** [comment]
@skorsch Can this be closed?

**Comment by skorsch** [comment]
> @skorsch Can this be closed?

Yeah it can but I was holding off in case we want an 'about' section? Could also just make it another task
