### ISSUE TITLE
Git Operations

### ISSUE THREAD

**Issue by keanelekenns** [devxp-ca/devxp#113]
Description: We would like to set up utilities to interact with our clients' git repos.
Due: Milestone 2
Time Est: 12 hours
Actual Time:

Requires:
- [x] #45 
- [x] ~~#29~~ (Removed from milestone 2)
- [x] #30 
- [x] ~~#33~~ (Removed from milestone 2)
- [x] #35

**Comment by DerekRobin** [comment]
Closing this since all items are either done, have been moved to Milestone 3, or won't be supported
