### ISSUE TITLE
Improved UI

### ISSUE THREAD

**Issue by keanelekenns** [devxp-ca/devxp#117]
Description: We would like to see a noticeable improvement in our user interface from milestone 1 to milestone 2.
Due: Milestone 2
Time estimations are non-applicable here, since the UI will continuously evolve over the project's life.

Requires:
- [x] #141
- [x] #63 
- [x] #145
- [x] #146
- [x] #164
- [x] #166
- ~~[ ] #147~~ (Moved to Milestone 3, needs more user feedback)
- [x] #148
- [x] #97 
- [x] #98 
- [x] #154 
- [x] #157 
- [x] #158

**Comment by DerekRobin** [comment]
For page buttons: https://mui.com/components/pagination/

**Comment by DerekRobin** [comment]
Closing since all of the items are either done or moved to M3
