### ISSUE TITLE
Populate previous settings upon selecting a repo

### ISSUE THREAD

**Issue by keanelekenns** [devxp-ca/devxp#157]
Currently we are able to retrieve a repository's settings upon selecting a new repo. The settings are retrieved in ToolManager.tsx inside the setSelectedRepoFromDrawer function. This task is to use those retrieved settings to populate the options in the GUI.

**Comment by DerekRobin** [comment]
Upon selecting a repo, if the repo has saved settings, the user is prompted:
`That repo has settings already saved. Would you like to load them? YES/NO?`
Then regardless of what they choose, when they press the submit button, if the repo already has settings saved, we ask them:
`That repo has settings already saved. Would you like to overwrite them? YES/NO?`

**Comment by skorsch** [comment]
(Closed this before seeing dereks comment) But currently there is frontend support for previous instance cards, needs testing with the database
