### ISSUE TITLE
Don't show tools until repo is selected

### ISSUE THREAD

**Issue by keanelekenns** [devxp-ca/devxp#158]
![image](https://user-images.githubusercontent.com/43152879/156244607-7874217e-56e7-47cf-82c3-f500eab29067.png)

Submitting settings when no repo is selected results in an error. Even worse, we will be loading previous settings whenever a repo is selected, which will undo any changes made. Therefore we should not allow users to configure anything until they choose a repo.

I suggest that we start by having a simple message like the one shown in the image above, but in the future we can allow the user to learn about the tools before selecting a repo.

**Comment by DerekRobin** [comment]
I am not sure if this is needed anymore because as of now, the user has no choice but select a repo before proceeding to the rest of the tool manager.

**Comment by keanelekenns** [comment]
Yes, I think in light of the new plan, we can scrap this.

**Comment by DerekRobin** [comment]
This has been changed so that the tools are shown and the user can select a repo at any point during the process.
