### ISSUE TITLE
Save backend s3 bucket / google storage bucket ID to database

### ISSUE THREAD

**Issue by brennanwilkes** [devxp-ca/devxp#161]
Depending on the provider, aws or google, an s3 or google storage bucket is being generated for the terraform backend to use. This ID is randomly generated (as opposed to coming from the user), but needs to be saved and retrieved from the database.

`              "bucket": "terraform-state-kzzptt1ktfmmzj7amnwx9279rwcgpy6osnvkjhp3gfzyh"`
It will look like this^

**Comment by keanelekenns** [comment]
@brennanwilkes  Is this a final submission or future extension?
