### ISSUE TITLE
Rewrite add instance options tile

### ISSUE THREAD

**Issue by skorsch** [devxp-ca/devxp#186]
- it should overlay the other tiles while options are open
- open/close buttons for all tiles?

**Comment by keanelekenns** [comment]
@skorsch Was this made before our meeting? I'm not sure I understand what is meant by tile here (or just the issue in general).

**Comment by skorsch** [comment]
@keanelekenns it was during the meeting, just a general rewrite for how the single tiles work, when they open they should overlay the other tiles, not move them around

**Comment by keanelekenns** [comment]
Ahh, okay thank you for the clarification. I think we can close this then because I made a more detailed version of this exact task in #193 without realizing this was the same thing
