### ISSUE TITLE
Create resource configuration modal

### ISSUE THREAD

**Issue by keanelekenns** [devxp-ca/devxp#193]
Essentially we want the existing resource configuration tile to become a modal that is centered and overlayed on top of the screen.

The main difference is that the resource type will not be configurable in this modal. This is covered by #192.

This brings some logic changes that will also likely need to be integrated with @brennanwilkes' new resource class (please update this description with more details if I am leaving something important out)

The new modal should contain just what is circled here (settings determined based on what specific resource type is selected in #192). Also, the delete button should only be present if the resource is being modified, but not if it is being created (this logic already exists)

![image](https://user-images.githubusercontent.com/43152879/158520447-d663a08e-3c74-4665-89c5-a799593ffd01.png)

**Comment by DerekRobin** [comment]
Pretty sure this is implemented already, although I am not sure who did it
![Screen Shot 2022-03-27 at 7 44 34 PM](https://user-images.githubusercontent.com/39247349/160317744-f1254ebb-70c5-4c83-9936-ab35afdef02b.png)
.
