### ISSUE TITLE
Terraform Options Submission Loading Animation

### ISSUE THREAD

**Issue by chrispetrone** [devxp-ca/devxp#200]
Something like https://mui.com/components/progress/ ,

Likely best to use an indeterminate loading animation.  possible we could stack a linear one over the modal so it looks like its part of it.

- [ ] State management to track submission, response
- [ ] Positioning over modal or overlay on screen

**Comment by keanelekenns** [comment]
Is this a duplicate of #184 ?

**Comment by keanelekenns** [comment]
Maybe you could put the extra details of this there and close this if so?
