### ISSUE TITLE
Submitting settings to a repo which doesn't have any commits fails

### ISSUE THREAD

**Issue by DerekRobin** [devxp-ca/devxp#204]
When submitting to a repo that has no commits made to it, the POST request fails.
The request returns the following:
```
error: "Error"
message: "Request failed with status code 409"
path: "/api/v1/settings"
status: 500
timestamp: "2022-03-18T02:30:08.693Z"
```

**Comment by DerekRobin** [comment]
Tagged as `need to have` as I suspect people will create a new repo to test our application.

**Comment by DerekRobin** [comment]
Changed to `nice to have` as there might not be an easy way around this. It would be good to have the error message that the user sees reflect why their submission might fail though.

**Comment by brennanwilkes** [comment]
Closing this with [78056dd](https://github.com/devxp-ca/devxp/commit/78056dd9a2d4605fa5a2e25974824ee53a31362e). The issue is not solved, but a high-quality error message is displayed
