### ISSUE TITLE
Submitting settings to a repo which has an open pull request from DevXP fails.

### ISSUE THREAD

**Issue by DerekRobin** [devxp-ca/devxp#205]
When submitting to a repo that has an open PR made by DevXP, the POST request fails.
The request returns the following:
```
error: "Error"
message: "Request failed with status code 422"
path: "/api/v1/settings"
status: 500
timestamp: "2022-03-18T02:33:33.456Z"
```

**Comment by DerekRobin** [comment]
Tagged as `need to have` as I can imagine someone submitting changes and then wanting to change something before they merge.

**Comment by DerekRobin** [comment]
Changed to `nice to have`  as there might not be an easy way around this. Might have to make it so the error message reflects what is happening.

**Comment by brennanwilkes** [comment]
I can't reproduce this, the PR is successfully updated. @chrispetrone does this happen for you?
![Screenshot from 2022-03-18 07-48-05](https://user-images.githubusercontent.com/30160079/159025383-94541229-267e-4ca4-98d3-ae9249efa363.png)

**Comment by DerekRobin** [comment]
So I am baffled by this error. I just ran into it again.
![Screen Shot 2022-03-27 at 4 46 17 PM](https://user-images.githubusercontent.com/39247349/160306462-95d4324d-c5c7-49e0-8a52-e9d4edcc929f.png)
The first POST to settings is successful as there are isn't an open PR in my repo, and the second is a failing one when there is an open PR in my repo.

**Comment by brennanwilkes** [comment]
422 implies that the request to GitHub was malformed. I wonder if the specific blob being committed has some illegal character in it?

**Comment by brennanwilkes** [comment]
Has @anyone encountered this? I still cannot reproduce. Maybe we can close this for now and re-open once we have better, more descriptive error message responses?

**Comment by DerekRobin** [comment]
I can't reproduce this either so maybe it was fixed or caused as a by-product of something else. Closing because it seems to be okay.
