### ISSUE TITLE
Footer Component

### ISSUE THREAD

**Issue by chrispetrone** [devxp-ca/devxp#212]
Footer component recommended in Feedback (on Landing Page)

- [ ] Contact Info

- [ ] Information

**Comment by chrispetrone** [comment]
This only doesn't show up on the homepage, even though it is there in the render.

<img width="476" alt="image" src="https://user-images.githubusercontent.com/19274822/159201590-3a9cf27d-968a-4c3c-9cd5-fa58f12ab064.png">

**Comment by DerekRobin** [comment]
It is a duplicate, closing
