### ISSUE TITLE
Handling Form Persistence

### ISSUE THREAD

**Issue by chrispetrone** [devxp-ca/devxp#213]
It sucks to lose all of the resources added upon

- Leaving the page
- Back arrow (beside Add Resource button)
- Wiki
- Clicking on tool manager

Possible solutions are

- [x] ~~Saving state locally (iirc, we discussed this and it was a bigger issue than it sounds)~~
- [x] Popup Modal to warn user they will lose their information without submission
- [x] Popup Modal matches MUI components
- [x] Alert occurs after BackButton press (beside Add Resource button)

A popup modal is probably the easiest and quickest option

**Comment by keanelekenns** [comment]
I implemented the remaining parts of this in #239
