### ISSUE TITLE
Wiki should open in new window

### ISSUE THREAD

**Issue by chrispetrone** [devxp-ca/devxp#214]

**Comment by keanelekenns** [comment]
@chrispetrone are you referring to #198 ? If so, I think the consensus is that it isn't worth the time to do this.

**Comment by chrispetrone** [comment]
Sorry @keanelekenns , I just meant it shouldn't navigate off our page and should instead open the link as a new tab.

Now that we have the alert, though, it won't affect the user too much if they go to the wiki before submitting their config.

**Comment by keanelekenns** [comment]
My bad @chrispetrone, that makes sense now and I think that could be a good change if everyone agrees.
