### ISSUE TITLE
Clicking "back" button from tool manager does not do anything

### ISSUE THREAD

**Issue by keanelekenns** [devxp-ca/devxp#219]
![image](https://user-images.githubusercontent.com/43152879/159355261-291ea936-9a10-4e93-a7b1-33e41dc8a0cd.png)

I have not investigated, but it could be related to #216.

@chrispetrone  could you take a look?

**Comment by chrispetrone** [comment]
My b i probably broke it

**Comment by chrispetrone** [comment]
Fixed, polished styling on `TerraformOptionsModal`, and fixed nested button dom error
