### ISSUE TITLE
Make tooltips hoverable

### ISSUE THREAD

**Issue by keanelekenns** [devxp-ca/devxp#237]
As of now, if you hover over the question mark, you get a tooltip. Many of these tooltips will have links, such as the Google Project Id tooltip. The problem is that as soon as the cursor moves way from the question mark, the tooltip goes away, but we need it to persist as long as the user stays hovered over the tooltip itself.

![image](https://user-images.githubusercontent.com/43152879/160196035-18dc3d34-87fe-41c8-97ca-4d223cd3b2de.png)

**Comment by DerekRobin** [comment]
Might be of use: https://stackoverflow.com/questions/54705254/how-to-keep-showing-the-popover-on-hovering-on-the-anchorel-and-popover-as-w

Although I don't understand enough what's going on in the post to implement it.
