### ISSUE TITLE
Make add Resource Modal Scrollable if too large

### ISSUE THREAD

**Issue by keanelekenns** [devxp-ca/devxp#242]
This might only be an issue for me because I have a smaller screen, but you never know what our users will have, so it is best to cover all cases. If we have time, we should make a limit for how much space this modal takes up (or any of the modals for that matter) and add a scrollbar if it takes up too much space as shown.

![image](https://user-images.githubusercontent.com/43152879/160550929-95d88126-1b11-4a0e-9517-aa146a0afcd7.png)

**Comment by keanelekenns** [comment]
I am still experiencing this issue: 
![image](https://user-images.githubusercontent.com/43152879/163250016-90f78638-3f32-4c7f-becd-fed6ef9a3ba2.png)

**Comment by DerekRobin** [comment]
Please checkout mobile-friendly-toolmanager and see if you still have the issue. The commit which fixed this is not on main yet.

**Comment by keanelekenns** [comment]
oh sorry, my bad. I'll check it out
