### ISSUE TITLE
Github api getFileByPath utility method

### ISSUE THREAD

**Issue by brennanwilkes** [devxp-ca/devxp#46]

**Comment by keanelekenns** [comment]
Is this for editing pre-existing config files? Wouldn't we just get this from our database? I guess reading it from GitHub ensures that it is up to date. Am I right about that?

**Comment by brennanwilkes** [comment]
Not sure this is needed, since with the pivot to terraform we're pretty much always writing to the same file. Plus, git seems to be able to automatically create diffs.
