### ISSUE TITLE
Buttons in Navbar do not render on mobile

### ISSUE THREAD

**Issue by DerekRobin** [devxp-ca/devxp#47]

**Comment by brennanwilkes** [comment]
![Screenshot from 2022-02-06 00-42-44](https://user-images.githubusercontent.com/30160079/152673615-3288ca92-6fa8-4739-a36d-e9beb7335f75.png)

**Comment by brennanwilkes** [comment]
Looks like the element is being explicitly hidden when the screen size is below a specific size. I'd guess the component has some kind of setting to prevent or change this, but worst case we can override this with our own CSS

**Comment by DerekRobin** [comment]
When the page is below 900px in width the buttons are hidden
