### ISSUE TITLE
Feature List

### ISSUE THREAD

**Issue by brennanwilkes** [devxp-ca/devxp#54]
Required for milestone 1.

**Comment by DerekRobin** [comment]
I think the feature list is supposed to be ongoing. Also, not all issue are features. 

I'm fine with using the template for features but I don't think all issues need to use the template.

**Comment by keanelekenns** [comment]
Yeah that's true, we probably want a better way of organizing them though. We can tag features with key feature and perhaps use the nested issues to include all the smaller issues that contribute to that feature. Nested issues are like this:

- [ ] subtask 1
- [ ] subtask 2
    - [ ] subsubtask 1
