### ISSUE TITLE
Dark/light themeing + switch

### ISSUE THREAD

**Issue by skorsch** [devxp-ca/devxp#58]
- [x] create the themes
- [x] make sure all components reference the same variable that dictates the theme
- [x] implementation of a switch for users to turn on or off light mode
- [x] mode should be cached for user

**Comment by skorsch** [comment]
@DerekRobin while I was adjusting colors I got caught up in this and ended up doing the 'make sure all components reference the same variable that dictates the theme', I can continue to adjust the colors of things etc. but all you need to change now is  `<ThemeProvider theme={lightTheme}>` in toolManager.tsx to darkTheme to get everything to change now, so just hook that value up to a button etc.

**Comment by DerekRobin** [comment]
@skorsch It still seems like somethings are not the correct colours such as the provider text in this photo
![Screen Shot 2022-03-27 at 11 04 25 AM](https://user-images.githubusercontent.com/39247349/160294612-e8798475-718f-4690-bc2a-9be4b21831fb.png)
I'll make an issue for it.

**Comment by DerekRobin** [comment]
Actually, it should be figured out. We just need to wrap everything in a <Paper> component and the text will auto switch

**Comment by skorsch** [comment]
@DerekRobin yeah i just didn't get everything color corrected yet, there are some that switch but others that don't which is why i had it set up that way
