### ISSUE TITLE
Select repo from list

### ISSUE THREAD

**Issue by keanelekenns** [devxp-ca/devxp#78]
- Feature name: Repository Selection
- Description: The user needs to be able to select a repo on the left sidebar in order to know what repo they are configuring settings for. In the future we may want to allow users to select multiple repos and configure them at the same time (or rather import settings from a repo to another repo), but for now we only need to support one repo configuring at a time.
- Requires: Adding an effect on the buttons in the sidebar (make it green or something) and store the current repo in a location that can be accessed by the logic that sends settings to the backend (this is where it will read the "repo_name" value from).
- Due: Milestone 1
- Status: We have a list of repo buttons, but they don't do anything.
- Time Estimation: 1 hour

**Comment by DerekRobin** [comment]
Repos in the list now have radio buttons where a **single** button is selectable as per [this commit](https://github.com/devxp-ca/devxp/commit/f555b2f2a1cca42fba8925bdf58f198ef6e8326c). There will still need to be a backend change to actually make the buttons do something.

**Comment by DerekRobin** [comment]
Reopening this issue because although you can select any repo you want, the request returns a [422 error](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422).

**Comment by DerekRobin** [comment]
Fixed so long as the repo you select is using main branch
