### ISSUE TITLE
Make status modal after receiving response from backend

### ISSUE THREAD

**Issue by keanelekenns** [devxp-ca/devxp#79]
- Feature name: Status Modal
- Description: Similar to #74, but after the work has been done by the backend and we have received a response from the backend. This will indicate either success or failure based on the response.
- Requires: Receiving response from backend and making a pop-up modal to inform the user of the response status.
- Due: Milestone 1.
- Status: Not started.
- Time Estimation: 1 hour.

**Comment by brennanwilkes** [comment]
Some inspiration: 
[Response component](https://github.com/brennanwilkes/gcs-radio/blob/master/src/frontend/Response/Response.tsx) with auto-queuing and rendering

Example of it being used: [](https://github.com/brennanwilkes/gcs-radio/blob/master/src/frontend/App/App.tsx)
